name: IOOS
channels:
  - conda-forge
dependencies:
  - python=3.13
  - bokeh
  - cartopy
  - cf_xarray
  - cf-units
  - ckanapi
  - compliance-checker
  - erddapy
  - folium
  - gdal
  - geopandas
  - geoplot
  - gridgeo
  - humanize
  - ioos_qc
  - ioos_tools
  - ioos-metrics
  - ipyleaflet
  - ipywidgets
  - jupyter
  - lxml
  - matplotlib-base
  - nbclassic
  - netcdf4
  - numpy
  - oceans
  - odvc
  - owslib
  - palettable
  - pandas
  - pocean-core
  - pyobis
  - pyoos
  - pysgrid
  - pyugrid
  - pyworms
  - requests
  - retrying
  - seawater
  - shapely
  - tqdm
  - xarray
  - zarr
  # R packages.
  - r-base=4
  - r-irkernel
  - r-dplyr
  - r-htmlwidgets
  - r-maps
  - r-readr
  - r-robis  # hoding osx-arm64
platforms:
  - linux-64
  - osx-64
  # - osx-arm64
  - win-64
