name: Test Data Analysis And Visualization Notebooks

on:
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Micromamba
        uses: mamba-org/setup-micromamba@068f1ab4b37ed9b3d9f73da7db90a0cda0a48d29 # v2.0.3
        with:
          environment-name: IOOS
          init-shell: bash
          create-args: >-
            --file .binder/conda-lock.yml

      - name: Notebook tests
        shell: bash -l {0}
        run: >
          micromamba install nbval
          && python -m pytest --nbval --nbval-lax jupyterbook/content/code_gallery/data_analysis_and_visualization_notebooks/
