name: Test Environment and link rot

on:
  pull_request:

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
      fail-fast: false
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Setup Micromamba
        uses: mamba-org/setup-micromamba@ab6bf8bf7403e8023a094abeec19d6753bdc143e #v1
        with:
          environment-name: IOOS
          init-shell: bash
          create-args: >-
            --file .binder/conda-lock.yml

      - name: Test environment
        run: >
          python -c 'import osgeo.gdal; print(dir(osgeo.gdal))'

      - name: Test links
        if: startsWith(matrix.os, 'ubuntu')
        run: >
          jupyter-book build jupyterbook --builder linkcheck
